### ISSUE TITLE
Hi, is this compatible with 1.16.2?

### ISSUE THREAD

**Issue by felix91gr** [Lemonszz/villager-hats#5]
Hi.

I don't know how the Fabric modding works, but I'm aware that many modders have had to work overtime after 1.16.2 was released because it broke a lot of stuff. Do you happen to know if this mod is already compatible with 1.16.2, Sam? Thanks.

**Comment by Lemonszz** [comment]
I'm not sure tbh. I'd hazard I guess and say yes, but it's untested.
